# 题目
Compute the centered and normalized homogeneous quadratic kernel matrix K for thedataset using the kernel function in input space.

Transform each point to the feature space o( x), using the homogeneous quadratickernel Center these points and normalize them.

Verify that the pair-wise dot products of the centered and normalized points in featurespace yield the same kernel matrix computed directly in input space via the kemelfunction.

# 计算核矩阵并中心化标准化
## 核矩阵
只要一个对称函数对应的核矩阵半正定，它就能作为核函数。
核矩阵K总是半正定的：
![Image of Yaktocat](https://private.codecogs.com/gif.latex?K%20%3D%20%5Cbegin%7Bbmatrix%7D%20%5Ckappa%20%28x_%7B1%7D%2Cx_%7B1%7D%29%20%26%20.%20%26%20.%20%26%20.%20%26%20%5Ckappa%20%28x_%7B1%7D%2Cx_%7Bm%7D%29%20%5C%5C%20.%20%26%20.%20%26%20.%20%26%20.%20%26%20.%5C%5C%20.%20%26%20.%20%26%20.%20%26%20.%20%26%20.%5C%5C%20.%20%26%20.%20%26%20.%20%26%20.%20%26%20.%5C%5C%20%5Ckappa%20%28x_%7Bm%7D%2Cx_%7B1%7D%29%20%26%20.%20%26%20.%20%26%20.%20%26%20%5Ckappa%20%28x_%7Bm%7D%2Cx_%7Bm%7D%29%20%5Cend%7Bbmatrix%7D)
核方法往简单地说，就是将一个低维的线性不可分的数据映射到一个高维的空间、并期望映射后的数据在高维空间里是线性可分的。我们以异或数据集为例：在二维空间中、异或数据集是线性不可分的；但是通过将其映射到三维空间、我们可以非常简单地让其在三维空间中变得线性可分。

核抄矩阵是样本之间通过核函数影射之后得到的，每两个样本之间进行一次核函数影射，N个样本就构成N*N维的核矩阵。

使用书中5.1
$${\rm{K}}(x,y)=x^Ty$$

## 标准化
矩阵标准化的目的是，通过标准化处理，得到均值为0，标准差为1的服从标准正态分布的数据。（相对一维数据来说，也就是相对矩阵的每一列，数据的每一个维度）.

矩阵标准化使用如下公式完成：
![Image of Yaktocat](https://www.zhihu.com/equation?tex=x%5E%7B%27%7D%3D%5Cfrac%7Bx-%5Cmu+%7D%7B%5Csigma+%7D++)
μ表示均值，σ表示标准差，（u和σ都可以看成是行向量形式，它们的每个元素分表表示矩阵每一列的均值和方差）可以看出矩阵中心化是矩阵标准化的一步，将中心化的矩阵除以标准差得到标准化矩阵。

当原始数据不同维度上的特征的尺度（单位）不一致时，需要标准化步骤对数据进行预处理。
下图中以二维数据为例：左图表示的是原始数据；中间的是中心化后的数据，数据被移动大原点周围；右图将中心化后的数据除以标准差，得到为标准化的数据，可以看出每个维度上的尺度是一致的（红色线段的长度表示尺度）。
![Image of Yaktocat](https://pic3.zhimg.com/80/v2-d232db445418e9edf404767ef441789f_720w.jpg)


In [35]:
import numpy as np
import pandas as pd

filepath = "C:\\Users\\Shinelon\\Desktop\\data-mining  project\\Project2\\iris.txt"
df = pd.read_csv(filepath)
# print(df)
df=df.iloc[:,[0,1,2,3]]  #除去最后一列
print(df)

df = df.values  #转换为数组
k=np.empty(shape=(149,149)) #生成空矩阵
for i in range(149):        #计算核矩阵
    for j in range(149):
        k[i][j]=np.dot(df[i],df[j])
print("核矩阵为：")
print(k)

mu = np.mean(k)   #计算均值
sigma = np.std(k) #计算标准差
cen1 = k - mu      #中心化矩阵
nor1 = (k-mu)/sigma#标准化矩阵
print("中心化矩阵为：")
print(cen1)
print("标准化矩阵为：")
print(nor1)


     5.9    3  4.2  1.5
0    6.9  3.1  4.9  1.5
1    6.6  2.9  4.6  1.3
2    4.6  3.2  1.4  0.2
3    6.0  2.2  4.0  1.0
4    4.7  3.2  1.3  0.2
..   ...  ...  ...  ...
144  5.4  3.4  1.7  0.2
145  5.5  2.6  4.4  1.2
146  6.7  3.0  5.2  2.3
147  7.7  3.8  6.7  2.2
148  5.1  3.4  1.5  0.2

[149 rows x 4 columns]
核矩阵为：
[[ 83.48  79.02  48.82 ...  84.46 101.04  53.38]
 [ 79.02  74.82  46.34 ...  79.83  95.52  50.68]
 [ 48.82  46.34  33.4  ...  48.16  57.4   36.48]
 ...
 [ 84.46  79.83  48.16 ...  86.22 102.89  52.63]
 [101.04  95.52  57.4  ... 102.89 123.46  62.68]
 [ 53.38  50.68  36.48 ...  52.63  62.68  39.86]]
中心化矩阵为：
[[ 24.47349489  20.01349489 -10.18650511 ...  25.45349489  42.03349489
   -5.62650511]
 [ 20.01349489  15.81349489 -12.66650511 ...  20.82349489  36.51349489
   -8.32650511]
 [-10.18650511 -12.66650511 -25.60650511 ... -10.84650511  -1.60650511
  -22.52650511]
 ...
 [ 25.45349489  20.82349489 -10.84650511 ...  27.21349489  43.88349489
   -6.37650511]
 [ 42.03349489  36.51

# 使用齐二次核将每个点变换到特征空间ϕ（x）
齐二次核矩阵$(\sqrt2*xy,x^2,y^2)$
可将四个属性扩展到十维
$(x_1{^2},x_2{^2},x_3{^2},x_4{^2},\sqrt2x_1x_2,\sqrt2x_2x_3, \sqrt2x_3x_4, \sqrt2x_1x_3, \sqrt2x_2x_4, \sqrt2x_1x_2)$

In [36]:
m=np.empty(shape=((149,10)))
for i in range (149):
    for j in range(4):
        m[i][j] = df[i][j]*df[i][j] 
        m[i][4] = np.sqrt(2) * df[i][0] * df[i][1]
        m[i][5] = np.sqrt(2) * df[i][0] * df[i][2]
        m[i][6] = np.sqrt(2) * df[i][0] * df[i][3]
        m[i][7] = np.sqrt(2) * df[i][1] * df[i][2]
        m[i][8] = np.sqrt(2) * df[i][1] * df[i][3]
        m[i][9] = np.sqrt(2) * df[i][2] * df[i][3]
print("齐二次核矩阵：")
print(m)

mu=np.mean(m)    #均值
sigma=np.std(m)  #标准差
nor2=(m-mu)/sigma #标准化
cen2=m-mu
print("标准化齐二次核矩阵：")
print(nor2)
print("中心化齐二次核矩阵：")
print(cen2)



齐二次核矩阵：
[[47.61        9.61       24.01       ... 21.48190401  6.57609307
  10.39446968]
 [43.56        8.41       21.16       ... 18.86560892  5.33158513
   8.4569971 ]
 [21.16       10.24        1.96       ...  6.33567676  0.90509668
   0.3959798 ]
 ...
 [44.89        9.         27.04       ... 22.06173157  9.75807358
  16.91399421]
 [59.29       14.44       44.89       ... 36.0058773  11.82282538
  20.84550791]
 [26.01       11.56        2.25       ...  7.21248917  0.96166522
   0.42426407]]
标准化齐二次核矩阵：
[[ 2.24122676 -0.46307089  0.56171559 ...  0.3818018  -0.67898109
  -0.40724354]
 [ 1.95300557 -0.54846977  0.35889326 ...  0.19561125 -0.7675474
  -0.54512518]
 [ 0.35889326 -0.41823648 -1.00748871 ... -0.69609049 -1.08256167
  -1.11879335]
 ...
 [ 2.04765598 -0.50648199  0.77734774 ...  0.42306565 -0.45253313
   0.05672317]
 [ 3.07244246 -0.11934043  2.04765598 ...  1.41541093 -0.30559356
   0.33651221]
 [ 0.70404704 -0.32429772 -0.98685065 ... -0.63369149 -1.07853593
  -1.11678047]

# 检验是否产生通过核函数在输入空间中直接计算出相同核矩阵


# 参考
https://github.com/carefree0910/MachineLearning/blob/master/Notebooks/SVM/zh-cn/Kernel%20Methods.ipynb

https://www.zhihu.com/question/37069477

https://blog.csdn.net/wsj998689aa/article/details/47027365
https://github.com/huhuzi1/data-minning/blob/master/label2/2.0.py
https://blog.csdn.net/qq_40245123/article/details/78399736